apiVersion: apps/v1
kind: Deployment
metadata:
  name: provision-log-queue-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provision-log-queue-consumer
  template:
    metadata:
      labels:
        app: provision-log-queue-consumer
    spec:
      containers:
        - name: provision-log-queue-consumer
          image: europe-north1-docker.pkg.dev/usit-itf-naic-project/vm-provisioning-docker-dev/provision-log-queue-consumer:latest
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: AUTH_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: api-key
