apiVersion: apps/v1
kind: Deployment
metadata:
  name: provision-request-queue-consumer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1          # Allow 1 extra pod during update
      maxUnavailable: 0    # Keep all pods running during update
  selector:
    matchLabels:
      app: provision-request-queue-consumer
  template:
    metadata:
      labels:
        app: provision-request-queue-consumer
    spec:
      containers:
        - name: provision-request-queue-consumer
          image: europe-north1-docker.pkg.dev/usit-itf-naic-project/vm-provisioning-docker/provision-request-queue-consumer:latest
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: TERRAFORM_RUNNER_IMAGE
              value: "<your-docker-registry>/terraform-runner:latest"
          volumeMounts:
            - name: terraform-volume
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: terraform-volume
          persistentVolumeClaim:
            claimName: terraform-wd-pvc
      serviceAccountName: rabbitmq-consumer-sa
