apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: amqp
  selector:
    app: rest-backend
