apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
spec:
  template:
    spec:
      containers:
        - name: terraform
          image: europe-north1-docker.pkg.dev/vm-provisioning/vm-provisioning-docker/tf-test:latest
          env:
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nrec-secret
                  key: username
            - name: OS_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: nrec-secret
                    key: password
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: nrec-secret
                  key: projectname
      restartPolicy: Never
  backoffLimit: 1
