export const VmStatusType = {
  UNKNOWN: 'UNKNOWN',
  TO_BE_PROVISIONED: 'TO_BE_PROVISIONED',
  PLANNING: 'PLANNING',
  PLANNING_COMPLETED: 'PLANNING_COMPLETED',
  PROVISIONING: 'PROVISIONING',
  PROVISIONING_COMPLETED: 'PROVISIONING_COMPLETED',
  PROVISIONING_FAILED: 'PROVISIONING_FAILED',
  INITIALIZING: 'INITIALIZING',
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
  SHUTDOWN: 'SHUTDOWN',
  TO_BE_DESTROYED: 'TO_BE_DESTROYED',
  DESTROYING: 'DESTROYING',
  DESTROYED: 'DESTROYED',
}

export type VmStatusType = typeof VmStatusType[keyof typeof VmStatusType]

export const validNextStates = {
  [VmStatusType.UNKNOWN]: [
    VmStatusType.TO_BE_PROVISIONED,
    VmStatusType.PLANNING,
    VmStatusType.PLANNING_COMPLETED,
    VmStatusType.PROVISIONING,
    VmStatusType.PROVISIONING_COMPLETED,
    VmStatusType.PROVISIONING_FAILED,
    VmStatusType.INITIALIZING,
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.TO_BE_PROVISIONED]: [
    VmStatusType.PLANNING,
    VmStatusType.PLANNING_COMPLETED,
    VmStatusType.PROVISIONING,
    VmStatusType.PROVISIONING_COMPLETED,
    VmStatusType.PROVISIONING_FAILED,
    VmStatusType.INITIALIZING,
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.PLANNING]: [
    VmStatusType.PLANNING_COMPLETED,
    VmStatusType.PROVISIONING,
    VmStatusType.PROVISIONING_COMPLETED,
    VmStatusType.PROVISIONING_FAILED,
    VmStatusType.INITIALIZING,
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.PLANNING_COMPLETED]: [
    VmStatusType.PROVISIONING,
    VmStatusType.PROVISIONING_COMPLETED,
    VmStatusType.PROVISIONING_FAILED,
    VmStatusType.INITIALIZING,
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.PROVISIONING]: [
    VmStatusType.PROVISIONING_COMPLETED,
    VmStatusType.PROVISIONING_FAILED,
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.PROVISIONING_COMPLETED]: [
    VmStatusType.INITIALIZING,
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  // [VmStatusType.PROVISIONING_FAILED]: [
  //   VmStatusType.PLANNING,
  //   VmStatusType.PLANNING_COMPLETED,
  //   VmStatusType.PROVISIONING,
  //   VmStatusType.RUNNING,
  //   VmStatusType.STOPPED,
  //   VmStatusType.SHUTDOWN,
  //   VmStatusType.DESTROYING,
  //   VmStatusType.DESTROYED,
  // ],
  [VmStatusType.INITIALIZING]: [
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.RUNNING]: [
    VmStatusType.STOPPED,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.STOPPED]: [
    VmStatusType.RUNNING,
    VmStatusType.SHUTDOWN,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.SHUTDOWN]: [
    VmStatusType.RUNNING,
    VmStatusType.STOPPED,
    VmStatusType.TO_BE_DESTROYED,
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.TO_BE_DESTROYED]: [
    VmStatusType.DESTROYING,
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.DESTROYING]: [
    VmStatusType.DESTROYED,
  ],
  [VmStatusType.DESTROYED]: [
    VmStatusType.DESTROYED,
  ],
}

export const URL_ACTION_TO_VM_STATUS_MAP = {
  NOTIFY_VM_INITIALIZE_START: VmStatusType.INITIALIZING,
  NOTIFY_VM_INITIALIZE_COMPLETE: VmStatusType.RUNNING,
  NOTIFY_VM_DESTROY_START: VmStatusType.DESTROYING,
}
