import { UrlAction, VmStatus } from '@prisma/client'

export const validNextStates: Record<VmStatus, VmStatus[]> = {
  [VmStatus.UNKNOWN]: [
    VmStatus.TO_BE_PROVISIONED,
    VmStatus.PLANNING,
    VmStatus.PLANNING_COMPLETED,
    VmStatus.PROVISIONING,
    VmStatus.PROVISIONING_COMPLETED,
    VmStatus.PROVISIONING_FAILED,
    VmStatus.INITIALIZING,
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.TO_BE_PROVISIONED]: [
    VmStatus.PLANNING,
    VmStatus.PLANNING_COMPLETED,
    VmStatus.PROVISIONING,
    VmStatus.PROVISIONING_COMPLETED,
    VmStatus.PROVISIONING_FAILED,
    VmStatus.INITIALIZING,
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.PLANNING]: [
    VmStatus.PLANNING_COMPLETED,
    VmStatus.PROVISIONING,
    VmStatus.PROVISIONING_COMPLETED,
    VmStatus.PROVISIONING_FAILED,
    VmStatus.INITIALIZING,
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.PLANNING_COMPLETED]: [
    VmStatus.PROVISIONING,
    VmStatus.PROVISIONING_COMPLETED,
    VmStatus.PROVISIONING_FAILED,
    VmStatus.INITIALIZING,
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.PROVISIONING]: [
    VmStatus.PROVISIONING_COMPLETED,
    VmStatus.PROVISIONING_FAILED,
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.PROVISIONING_COMPLETED]: [
    VmStatus.INITIALIZING,
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.PROVISIONING_FAILED]: [
    VmStatus.PLANNING,
    VmStatus.PLANNING_COMPLETED,
    VmStatus.PROVISIONING,
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.INITIALIZING]: [
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.RUNNING]: [
    VmStatus.STOPPED,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.STOPPED]: [
    VmStatus.RUNNING,
    VmStatus.SHUTDOWN,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.SHUTDOWN]: [
    VmStatus.RUNNING,
    VmStatus.STOPPED,
    VmStatus.TO_BE_DESTROYED,
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.TO_BE_DESTROYED]: [
    VmStatus.DESTROYING,
    VmStatus.DESTROYED,
  ],
  [VmStatus.DESTROYING]: [
    VmStatus.DESTROYED,
  ],
  [VmStatus.DESTROYED]: [
    VmStatus.DESTROYED,
  ],
}

export const URL_ACTION_TO_VM_STATUS_MAP = {
  [UrlAction.NOTIFY_VM_INITIALIZE_START]: VmStatus.INITIALIZING,
  [UrlAction.NOTIFY_VM_INITIALIZE_COMPLETE]: VmStatus.RUNNING,
  [UrlAction.NOTIFY_VM_DESTROY_START]: VmStatus.DESTROYING,
}
