apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraform-wd-filestore-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs_share  # The name of the Filestore file share
    server: 10.166.0.21  # Internal IP address of the NFS Share instance
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-filestore-sc
