apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-wd-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: terraform-wd-filestore-pv
  storageClassName: my-filestore-sc
