#cloud-config

bootcmd:
  - |
    curl -X POST -d "status=boot_started" ${init_boot_call_url}

write_files:
  - path: /etc/profile.d/eessi_init.sh
    content: |
      EESSI_SILENT=True
      
      # Save the current PS1 value
      ORIGINAL_PS1=$PS1

      # Setting up the EESSI environment
      source /cvmfs/software.eessi.io/versions/2023.06/init/bash

      # Restore the original PS1 value
      export PS1=$ORIGINAL_PS1
      
      echo "Thank you for using NAIC Orchestrator - Self Service VM Portal!"

permissions: '0755'

#cloud-config

runcmd:
  - |
    if [ -f /etc/redhat-release ]; then
      curl -s https://raw.githubusercontent.com/NAICNO/vm-provision-scripts/master/cloud-init/rhel.sh | bash
    fi
  - |
    if [ -f /etc/debian_version ]; then
      curl -s https://raw.githubusercontent.com/NAICNO/vm-provision-scripts/master/cloud-init/debian.sh | bash
    fi
  - |
    if [ -n "${jupyter_token}" ]; then
      # Fetch Jupyter init script
      curl -fsSL "https://raw.githubusercontent.com/NAICNO/vm-provision-scripts/refs/heads/master/cloud-init/projects/jupyter-notebook/jupyter_init.sh" -o /usr/local/bin/jupyter_init.sh
      chmod 0755 /usr/local/bin/jupyter_init.sh
      # Run script as specified user with token and optional URLs
      su - ${username} -c "bash -lc '/usr/local/bin/jupyter_init.sh \"${jupyter_token}\" \"${jupyter_init_start_url}\" \"${jupyter_init_complete_url}\"'"
    fi

phone_home:
  url: ${phone_home_url}
  post:
    - instance_id
    - hostname
    - fqdn
  tries: 5
