export const VmEventType = {
  PROVISIONING_REQUESTED: 'PROVISIONING_REQUESTED',
  PROVISIONING_QUEUED: 'PROVISIONING_QUEUED',
  PROVISIONING_STARTED: 'PROVISIONING_STARTED',
  PROVISIONING_COMPLETED: 'PROVISIONING_COMPLETED',
  PROVISIONING_FAILED: 'PROVISIONING_FAILED',
  DESTROYING_REQUESTED: 'DESTROYING_REQUESTED',
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
  SHUTDOWN: 'SHUTDOWN',
  UNKNOWN: 'UNKNOWN',
}

export type VmEventType = typeof VmEventType[keyof typeof VmEventType]
