export const VmStatusType = {
  TO_BE_PROVISIONED: 'TO_BE_PROVISIONED',
  PROVISIONING: 'PROVISIONING',
  PROVISIONING_COMPLETED: 'PROVISIONING_COMPLETED',
  PROVISIONING_FAILED: 'PROVISIONING_FAILED',
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
  SHUTDOWN: 'SHUTDOWN',
  UNKNOWN: 'UNKNOWN',
}

export type VmStatusType = typeof VmStatusType[keyof typeof VmStatusType]
