apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraform-wd-filestore-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /tf_wd_share  # The name of the Filestore file share
    server: 10.30.63.226  # IP address of the Filestore instance
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-filestore-sc
